# TP3 --- DÉTERMINANTS

[Python 3 -- testé avec Python 3.8.5]

Le but de ce TP est de calculer le déterminant de matrices carrées de taille quelconque, à l'aide d'opérations simples sur les coefficients.

Chargement des paquets utiles :

In [1]:
import numpy as np

## 0. Commandes utiles

Voici quelques commandes utiles dont vous pourrez avoir besoin dans ce TP. La commande `np.array` transforme une liste de listes en une matrice. Ainsi, une matrice $M = (a_{i, j})_{\substack{0 \leqslant i < n \\ 0 \leqslant j < p}} \in \mathcal{M}_{n, p}(\mathbb{R})$ sera représentée par un tableau `M` (de type `ndarray`) grâce à la commande :
```
M = np.array([[a_00, ..., a_0(p-1)], ..., [a_(n-1)0, ..., a_(n-1)(p-1)]], dtype=float)
```

**Attention** : Pour suivre la convention de Python, nous numéroterons les coefficients à partir de $0$.

**Attention** : Pour travailler avec des réels, nous précisons bien l'option `dtype=float`.

Alors :
- `np.shape(M)` renvoie la taille $(n, p)$ de $M$ ;
- `M[i, j]` renvoie le coefficient $a_{i, j}$ ;
- `M[i, :]` renvoie la ligne $i$ de $M$ ;
- `M[:, j]` renvoie la colonne $j$ de $M$ ;
- `M[i1:i2, j1:j2]` renvoie la matrice extraite $(a_{i, j})_{\substack{i_1 \leqslant i < i_2 \\ j_1 \leqslant j < j_2}}$ ;
- `np.delete(M, i, axis=0)` renvoie la matrice obtenue à partir de $M$ en supprimant la ligne $i$ ;
- `np.delete(M, j, axis=1)` renvoie la matrice obtenue à partir de $M$ en supprimant la colonne $j$.

Observer et comprendre les commandes ci-dessous.

In [2]:
M = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]], dtype=float)
print("M =\n", M)
print("np.shape(M) =", np.shape(M))
print("M[0, 2] =\n", M[0, 2])
print("M[0, :] =\n", M[0, :])
print("M[:, 1] =\n", M[:, 1])
print("M[1:3, 2:4] =\n", M[1:3, 2:4])

M =
 [[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]
np.shape(M) = (3, 4)
M[0, 2] =
 3.0
M[0, :] =
 [1. 2. 3. 4.]
M[:, 1] =
 [ 2.  6. 10.]
M[1:3, 2:4] =
 [[ 7.  8.]
 [11. 12.]]


On peut ainsi multiplier une ligne d'une matrice par un nombre, ou remplacer une ligne par elle-même plus (un multiple d')une autre :

In [3]:
M = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]], dtype=float)
print(M)

M[0, :] = 4 * M[0, :]
print(M)

M[1, :] = M[1, :] + M[2, :]
print(M)

M[2, :] = M[2, :] - 2 * M[0, :]
print(M)

[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]
[[ 4.  8. 12. 16.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]
[[ 4.  8. 12. 16.]
 [14. 16. 18. 20.]
 [ 9. 10. 11. 12.]]
[[  4.   8.  12.  16.]
 [ 14.  16.  18.  20.]
 [  1.  -6. -13. -20.]]


**Attention** : Quand on affecte une sous-matrice à une nouvelle matrice, l'espace mémoire n'est pas dupliqué. Pour dupliquer l'expace mémoire il faut créer une nouvelle matrice avec `np.array`. Comparer les deux blocs suivants.

In [4]:
M = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]], dtype=float)

print("M =\n", M)

L_1 = M[1, :]    # L_1 pointe vers la ligne 1 de la matrice M.
L_1[1] = 0

print("L_1 =\n", L_1)
print("M =\n", M)

M =
 [[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]
L_1 =
 [5. 0. 7. 8.]
M =
 [[ 1.  2.  3.  4.]
 [ 5.  0.  7.  8.]
 [ 9. 10. 11. 12.]]


In [5]:
M = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]], dtype=float)

print("M =\n", M)

L_1 = np.array(M[1, :])    # L_1 est une nouvelle matrice, indépendante de M.
L_1[1] = 0

print("L_1 =\n", L_1)
print("M =\n", M)

M =
 [[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]
L_1 =
 [5. 0. 7. 8.]
M =
 [[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]


Enfin, pour supprimer une rangée (ligne ou colonne) dans une matrice, on utilise la fonction `np.delete`. Observer et comprendre les commandes ci-dessous.

In [6]:
M = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]], dtype=float)
print("M =\n", M)

print("np.delete(M, 1, axis=0) =\n", np.delete(M, 1, axis=0))
print("np.delete(M, 1, axis=1) =\n", np.delete(M, 1, axis=1))

M =
 [[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]
np.delete(M, 1, axis=0) =
 [[ 1.  2.  3.  4.]
 [ 9. 10. 11. 12.]]
np.delete(M, 1, axis=1) =
 [[ 1.  3.  4.]
 [ 5.  7.  8.]
 [ 9. 11. 12.]]


## 1. Calcul du déterminant par développement suivant une ligne

### 1.1. Déterminants d'ordre 2

Écrire une fonction `det_2(A)` qui prend en entrée une matrice carrée `A` de taille $2$ et qui renvoie son déterminant.

In [7]:
def det_2(A):
    # Solution
    return A[0][0] * A[1][1] - A[1][0]*A[0][1]
    # Fin solution

Tester la fonction `det_2(A)` avec les matrices
$$
B_1 = \begin{pmatrix}
1 & 2 \\
4 & 3
\end{pmatrix}
\quad \text{et} \quad
B_2 = \begin{pmatrix}
6 & 3 \\
2 & 1
\end{pmatrix} .
$$

In [8]:
# Solution
B_1 = np.array([[1,2], [4,3]], dtype=float)
B_2 = np.array([[6,3], [2,1]], dtype=float)
print("detB1 = ",det_2(B_1))
print("detB2 = ",det_2(B_2))
# Fin solution

detB1 =  -5.0
detB2 =  0.0


### 1.2. Déterminants d'ordre 3

Il est possible de calculer le déterminant d'une matrice de taille $3$ de plusieurs façons. Nous nous intéressons à celle qui utilise le développement suivant la ligne $0$.

On donne la fonction `extr_3_2(A, i, j)` qui prend en entrée :
- une matrice carrée `A` de taille $3$,
- un numéro de ligne `i`
- et un numéro de colonne `j`,

et qui renvoie la matrice obtenue à partir de `A` en supprimant la ligne `i` et la colonne `j` (matrice extraite).

In [9]:
def extr_3_2(A, i, j):
    A_extraite = np.array(A)    
    A_extraite = np.delete(A_extraite, i, axis=0)
    A_extraite = np.delete(A_extraite, j, axis=1)
    return A_extraite

Tester la fonction `extr_3_2` avec la matrice
$$
A_1 = \begin{pmatrix}
0 & -1 & 4 \\
5 & 0 & 3 \\
6 & -6 & 1
\end{pmatrix}
$$
et
- en supprimant la ligne $1$ et la colonne $0$ ;
- en supprimant la ligne $1$ et la colonne $2$.

In [10]:
A_1 = np.array([[0, -1, 4], [5, 0, 3], [6, -6, 1]], dtype=float)

# Solution
print("extraction [1,0]",extr_3_2(A_1, 1, 0),"\n")
print("extraction [1,2]",extr_3_2(A_1, 1, 2))
# Fin solution

extraction [1,0] [[-1.  4.]
 [-6.  1.]] 

extraction [1,2] [[ 0. -1.]
 [ 6. -6.]]


Écrire une fontion `det_3(A)` qui prend en entrée une matrice carrée `A` de taille $3$ et qui calcule son déterminant en le développant suivant la première ligne et en faisant appel à `extr_3_2` et à `det_2`.

In [11]:
def det_3(A):
    # Solution
    return A[0, 0] * det_2(extr_3_2(A, 0, 0)) \
            - A[0, 1] * det_2(extr_3_2(A, 0, 1)) \
            + A[0, 2] * det_2(extr_3_2(A, 0, 2))
    # Fin solution

Tester la fonction `det_3(A)` sur les matrices $A_1$ (définie ci-dessus) et
$$
A_2 = \begin{pmatrix}
1 & 4 & -2 \\
1 & -2 & 4 \\
5 & 7 & 3
\end{pmatrix} .
$$

In [34]:
A_1 = np.array([[0, -1, 4], [5, 0, 3], [6, -6, 1]])
A_2 = np.array([[1, 4, -2], [1, -2, 4], [5, 7, 3]])

print("det(A_1) =", det_3(A_1))
print("det(A_2) =", det_3(A_2))

det(A_1) = -133
det(A_2) = 0


### 1.3. Déterminants d'ordre quelconque

On donne ci-dessous la fonction `determinant(A)` qui prend en entrée une matrice carrée `A` de taille quelconque et renvoie son déterminant en le développant suivant la première ligne. On notera qu'on fait appel, à l'intérieur du code, à la fonction `determinant` elle-même (on parle de fonction *récursive*).

In [29]:
def determinant(A):
    (n, p) = np.shape(A)    # On récupère ainsi la taille (n, p) de la matrice A.
    
    if n == 1:
        return A[0, 0]
    
    else:
        resultat = 0
        A_1 = np.array(A)
        A_1 = np.delete(A_1, 0, axis=0)
        
        for j in range(n):
            A_2 = np.delete(A_1, j, axis=1)
            resultat += (-1)**j * A[0, j] * determinant(A_2)
        
        return resultat

Tester la fonction `determinant(A)` sur les matrices $A_1$, $A_2$ (définies ci-dessus),
$$
A_3 = \begin{pmatrix}
1 & 4 & 7 & 10 \\
-2 & 3.3 & -14 & 0 \\
1 & 1.32 & 7 & 0.01 \\
0 & -8 & 0 & 41
\end{pmatrix}
\quad \text{et} \quad
A_4 = \begin{pmatrix}
1 & 5 & 8 & 1.5 & 7 & -8 \\
0 & 7 & 0 & -2.2 & 4 & 0 \\
0 & 0 & -3 & 1 & -0.4 & 5 \\
0 & 0 & 0 & 2 & 4 & 1.1 \\
0 & 0 & 0 & 0 & 5 & 2 \\
0 & 0 & 0 & 0 & 0 & 1.5
\end{pmatrix} .
$$

In [30]:
A_1 = np.array([[0, -1, 4], [5, 0, 3], [6, -6, 1]], dtype=float)
A_2 = np.array([[1, 4, -2], [1, -2, 4], [5, 7, 3]], dtype=float)
A_3 = np.array([[1, 4, 7, 10],[-2, 3.3, -14, 0], [1, 1.32, 7, 0.01], [0, -8, 0, 41]], dtype=float)
A_4 = np.array([[1, 5, 8, 1.5, 7, -8],
              [0, 7, 0, -2.2, 4, 0],
              [0, 0, -3, 1, -0.4, 5],
              [0, 0, 0, 2, 4, 11],
              [0, 0, 0, 0, 5, 2],
              [0, 0, 0, 0, 0, 1.5]], dtype=float)


print("det(A_1) =", determinant(A_1))
print("det(A_2) =", determinant(A_2))
print("det(A_3) =", determinant(A_3))
print("det(A_4) =", determinant(A_4))

det(A_1) = -133.0
det(A_2) = 0.0
det(A_3) = 2.2737367544323206e-13
det(A_4) = -315.0


## 2. Amélioration : calcul du déterminant à l'aide de l'algorithme du pivot de Gauss

### 2.1. Un premier exemple

On souhaite calculer le déterminant suivant :
$$
\Delta
 = \begin{vmatrix}
2 & 4 & -1 \\
4 & 0 & -2 \\
1 & 2 & 1
\end{vmatrix} .
$$

Définir la matrice `A` dont on va calculer le déterminant.

In [35]:
# Solution
A = np.array([[2, 4, -1], [4, 0, -2], [1, 2, 1]],dtype=float)
print("A =\n", A)
# Fin solution

A =
 [[ 2.  4. -1.]
 [ 4.  0. -2.]
 [ 1.  2.  1.]]


On va calculer le déterminant $\Delta$ en utilisant la méthode du pivot de Gauss pour se ramener à un déterminant triangulaire supérieur. Les seules opérations élémentaires autorisées sont :
- les **permutations** de lignes $L_i \leftrightarrow L_j$ ($i \neq j$) ;
- les **dilatations** de lignes $L_i \leftarrow \alpha L_i$ ($\alpha \in \mathbb{R} \setminus \{ 0 \}$) ;
- et les **transvections** sur les lignes $L_i \leftarrow L_i + \beta L_j$ ($i \neq j$ et $\beta \in \mathbb{R}$).

Comme ces opérations changent la valeur du déterminant, on introduira en plus de la matrice `A` une variable `resultat` : on partira de `resultat = 1` et, à chaque opération élémentaire effectuée, on actualisera la valeur de `resultat` de sorte que le produit du déterminant de la matrice obtenue `A_modifiee` et de `resultat` soit toujours égal à $\Delta$.

Effectuer sur la matrice `A` les opérations élémentaires correspondant à l'algorithme du pivot de Gauss et qui aboutissent à une matrice de la forme
$$
A_{\text{triangulaire}} =
\begin{pmatrix}
1 & * & * \\
0 & 1 & * \\
0 & 0 & 1
\end{pmatrix} ,
$$
sans oublier d'actualiser la valeur de `resultat`.

In [37]:
A_modifiee = np.array(A)
resultat = 1

# Solution
A_modifiee[0, :] = 1 / 2 * A_modifiee[0, :]
resultat = 2 * resultat
A_modifiee[1, :] = A_modifiee[1, :] - 4 * A_modifiee[0, :]
resultat = resultat
A_modifiee[2, :] = A_modifiee[2, :] - A_modifiee[0, :]
resultat = resultat
print((A_modifiee, resultat))

A_modifiee[1, :] = -1 / 8 * A_modifiee[1, :]
resultat = -8 * resultat
A_modifiee[2, :] = 1 / 1.5 * A_modifiee[2, :]
resultat = 1.5 * resultat
print((A_modifiee, resultat))
# Fin solution

(array([[ 1. ,  2. , -0.5],
       [ 0. , -8. ,  0. ],
       [ 0. ,  0. ,  1.5]]), 2)
(array([[ 1. ,  2. , -0.5],
       [-0. ,  1. , -0. ],
       [ 0. ,  0. ,  1. ]]), -24.0)


On peut vérifier le résultat obtenu à l'aide de la fonction `np.linalg.det` :

In [17]:
np.linalg.det(A)

-23.999999999999993

### 2.2 Opérations élémentaires

On définit la fonction `Permutation(A, resultat, i, j)` qui renvoie le couple `(A_modifiee, resultat_modifie)` où :
- `A_modifiee` est la matrice obtenue à partir d'une matrice `A` en échangeant les lignes `i` et `j` ;
- `resultat_modifie` est le nombre tel que le produit du déterminant de `A` et de `resultat` soit égal au produit du déterminant de `A_modifiee` et de `resultat_modifie`.

In [38]:
def Permutation(A, resultat, i, j):
    A_modifiee = np.array(A)    # On copie la matrice A pour que la matrice A elle-même ne soit pas modifiée.
    
    if i == j:
        return (A_modifiee, resultat)    # Cas où on ne permute rien du tout...
    
    else:
        A_modifiee[i, :] = A[j, :]
        A_modifiee[j, :] = A[i, :]
        return (A_modifiee, -resultat)    # Quand on échange deux lignes, le déterminant change de signe.

Définir de même des fonctions `Dilatation(A, resultat, i, alpha)` et `Transvection(A, resultat, i, j, beta)` qui prennent en argument une matrice `A`, un nombre `resultat` et les paramètres d'une opération élémentaire sur les lignes (définie dans la section 2), et renvoient le couple `(A_modifiee, resultat_modifie)` où `A_modifiee` est la matrice modifiée en conséquence et `resultat_modifie` la mise à jour de `resultat` pour que le produit du déterminant de `A` et de `resultat` soit égal au produit du déterminant de `A_modifiee` et de `resultat_modifie`.

In [73]:
def Dilatation(A, resultat, i, alpha):
    # Solution
    A_modifiee = np.array(A)
    A_modifiee[i, :] = alpha * A_modifiee[i, :]
    return (A_modifiee, resultat / alpha)
    # Fin solution

def Transvection(A, resultat, i, j, beta):
    # Solution
    A_modifiee = np.array(A)
    A_modifiee[i, :] = A_modifiee[i, :] + beta * A_modifiee[j, :]
    return (A_modifiee, resultat)
    # Fin solution

Tester les fonctions `Permutation(A, resultat, i, j)`, `Dilatation(A, resultat, i, alpha)` et `Transvection(A, resultat, i, j, beta)` sur la matrice
$$
A_3 = \begin{pmatrix}
1 & 4 & 7 & 10 \\
-2 & 3.3 & -14 & 0 \\
1 & 1.32 & 7 & 0.01 \\
0 & -8 & 0 & 41
\end{pmatrix} .
$$

In [74]:
A_3 = np.array([[1, 4, 7, 10],[-2, 3.3, -14, 0], [1, 1.32, 7, 0.01], [0, -8, 0, 41]], dtype=float)
print("A_3 =\n", A_3)

# Solution
print("Permutation(A_3, 1, 3, 2) =\n", Permutation(A_3, 1, 3, 2))
print("Dilatation(A_3, 1, 2, 1/2) =\n", Dilatation(A_3, 1, 2, 1/2))
print("Transvection(A_3, 1, 3, 0, -3) =\n", Transvection(A_3, 1, 3, 0, -3))
# Fin solution

A_3 =
 [[ 1.00e+00  4.00e+00  7.00e+00  1.00e+01]
 [-2.00e+00  3.30e+00 -1.40e+01  0.00e+00]
 [ 1.00e+00  1.32e+00  7.00e+00  1.00e-02]
 [ 0.00e+00 -8.00e+00  0.00e+00  4.10e+01]]
Permutation(A_3, 1, 3, 2) =
 (array([[ 1.00e+00,  4.00e+00,  7.00e+00,  1.00e+01],
       [-2.00e+00,  3.30e+00, -1.40e+01,  0.00e+00],
       [ 0.00e+00, -8.00e+00,  0.00e+00,  4.10e+01],
       [ 1.00e+00,  1.32e+00,  7.00e+00,  1.00e-02]]), -1)
Dilatation(A_3, 1, 2, 1/2) =
 (array([[ 1.0e+00,  4.0e+00,  7.0e+00,  1.0e+01],
       [-2.0e+00,  3.3e+00, -1.4e+01,  0.0e+00],
       [ 5.0e-01,  6.6e-01,  3.5e+00,  5.0e-03],
       [ 0.0e+00, -8.0e+00,  0.0e+00,  4.1e+01]]), 2.0)
Transvection(A_3, 1, 3, 0, -3) =
 (array([[ 1.00e+00,  4.00e+00,  7.00e+00,  1.00e+01],
       [-2.00e+00,  3.30e+00, -1.40e+01,  0.00e+00],
       [ 1.00e+00,  1.32e+00,  7.00e+00,  1.00e-02],
       [-3.00e+00, -2.00e+01, -2.10e+01,  1.10e+01]]), 1)


Écrire une fonction `SuiteTransvections(A, resultat, beta)` qui prend en argument une matrice carrée `A` à $n$ lignes, un nombre `resultat` et une liste `beta` contenant $n - 1$ scalaires $\beta_1$, ..., $\beta_{n-1}$, et qui renvoie le couple `(A_modifiee, resultat_modifie)` où `A_modifiee` est la matrice obtenue en transformant `A` par la suite d'opérations :
\begin{align*}
L_1 & \leftarrow L_1 + \beta_1 L_0 , \\
L_2 & \leftarrow L_2 + \beta_2 L_0 , \\
& \vdots \\
L_{n-1} & \leftarrow L_{n-1} + \beta_{n-1} L_0
\end{align*}
et `resultat_modifie` est le nombre tel que le produit du déterminant de `A` et de `resultat` soit égal au produit du déterminant de `A_modifiee` et de `resultat_modifie`.

In [89]:
def SuiteTransvections(A, resultat, beta):
    (n, p) = np.shape(A)  
    A_modifiee = np.array(A)  
    
    # Solution
    for i in range(1, n):
        
        (A_modifiee, resultat_modifiee) = Transvection(A_modifiee, resultat, i, 0, beta[i - 1])
   
    return (A_modifiee, resultat_modifiee)

    # Fin solution

Tester la fonction `SuiteTransvections(A, resultat, beta)` sur la matrice $A_3$.

In [90]:
SuiteTransvections(A_3, 1, [2, -1, 0])

(array([[ 1.  ,  4.  ,  7.  , 10.  ],
        [ 0.  , 11.3 ,  0.  , 20.  ],
        [ 0.  , -2.68,  0.  , -9.99],
        [ 0.  , -8.  ,  0.  , 41.  ]]),
 1)

### 2.3. Choix d'un pivot

Définir une fonction `ChoixPivot(A, resultat)` qui prend en argument une matrice carrée `A` de taille quelconque et un nombre `resultat` et renvoie un couple `(A_choix, resultat_choix)` où :
- `A_choix` est obtenue à partir de `A` en trouvant dans la colonne $0$ de `A` un élément non nul (pivot), puis en permutant et dilatant des lignes de sorte que le pivot soit en ligne $0$ et égal à $1$ ;
- `resultat_choix` est le nombre tel que le produit du déterminant de `A` et de `resultat` soit égal au produit du déterminant de `A_choix` et de `resultat_choix`.

Si ce n'est pas possible, autrement dit si la colonne $0$ de `A` est nulle, la fonction renvoie le couple `(A, 0)`.

Pour trouver un élément non nul, on choisira l'élément de valeur absolue maximale en utilisant les fonctions `abs` et `np.argmax`.

In [86]:
def ChoixPivot(A, resultat):
    i = np.argmax(abs(A[:, 0]))
    # Solution
    a = A[i, 0]
    
    if abs(a) == 0:    # Variante : if abs(a) < 10**(-100):
        return (A, 0)
    
    else:
        (A_1, resultat_1) = Permutation(A, resultat, 0, i)
        return Dilatation(A_1, resultat_1, 0, (1 / a))
    # Fin solution

Tester la fonction `ChoixPivot(A, resultat)` sur les matrices suivantes : $A_1$ (définie dans la section 1.2), `A_5 = A` (définie dans la section 2.1),
$$
A_6 = \begin{pmatrix}
0 & 1 & 0 \\
0 & 0 & 2 \\
0 & 3 & -1
\end{pmatrix}
$$
et `A_7 = np.random.randn(9, 9)` (matrice aléatoire).

In [85]:
# A_1
A_1 = np.array([[0, -1, 4], [5, 0, 3], [6, -6, 1]], dtype=float)
print("A_1 =\n", A_1)

(A_1_choix, resultat_1_choix) = ChoixPivot(A_1, 1)
print("(A_1_choix, resultat_1_choix) =\n", (A_1_choix, resultat_1_choix))

# A_5
A_5 = A
print("A_5 =\n", A_5)

(A_5_choix, resultat_5_choix) = ChoixPivot(A_5, 1)
print("(A_5_choix, resultat_5_choix) =\n", (A_5_choix, resultat_5_choix))

# A_6
A_6 = np.array([[0, 1, 0], [0, 0, 2], [0, 3, -1]], dtype=float)
print("A_6 =\n", A_6)

(A_6_choix, resultat_6_choix) = ChoixPivot(A_6, 1)
print("(A_6_choix, resultat_6_choix) =\n", (A_6_choix, resultat_6_choix))

# A_7
A_7 = np.random.randn(9, 9)
print("A_7 =\n", np.round(A_7, 2))    # On arrondit les valeurs seulement pour l'affichage.

(A_7_choix, resultat_7_choix) = ChoixPivot(A_7, 1)
print("(A_7_choix, resultat_7_choix) =\n", (np.round(A_7_choix, 2), resultat_7_choix))

A_1 =
 [[ 0. -1.  4.]
 [ 5.  0.  3.]
 [ 6. -6.  1.]]
(A_1_choix, resultat_1_choix) =
 (array([[ 1.        , -1.        ,  0.16666667],
       [ 5.        ,  0.        ,  3.        ],
       [ 0.        , -1.        ,  4.        ]]), -6.0)
A_5 =
 [[ 2.  4. -1.]
 [ 4.  0. -2.]
 [ 1.  2.  1.]]
(A_5_choix, resultat_5_choix) =
 (array([[ 1. ,  0. , -0.5],
       [ 2. ,  4. , -1. ],
       [ 1. ,  2. ,  1. ]]), -4.0)
A_6 =
 [[ 0.  1.  0.]
 [ 0.  0.  2.]
 [ 0.  3. -1.]]
(A_6_choix, resultat_6_choix) =
 (array([[ 0.,  1.,  0.],
       [ 0.,  0.,  2.],
       [ 0.,  3., -1.]]), 0)
A_7 =
 [[-0.89 -0.67 -0.18  0.66 -1.16 -1.33 -0.17  1.41  0.28]
 [ 0.63 -1.09  0.35  0.33 -0.   -0.14  1.21  0.43  1.55]
 [-0.17 -1.84  0.52 -0.21  0.91  0.79  0.27 -0.13  0.31]
 [-0.84 -0.78  1.19  0.    2.05 -1.03 -2.32  0.41  1.24]
 [ 1.74 -0.73 -0.35  2.62  0.49  0.57 -0.53 -0.04 -0.29]
 [-0.12  1.2   0.07  1.83  1.06 -0.87 -0.28 -1.88  1.17]
 [-0.11 -1.75 -1.35  1.62 -0.41  0.58  0.34  0.25  0.08]
 [-0.58 -0.36 -

### 2.4. Élimination à l'aide du pivot

On donne la fonction `EliminationPivot(A_choix, resultat_choix)` qui prend en argument une matrice carrée `A_choix` de taille quelconque et un nombre `resultat_choix` obtenus comme sortie de la fonction `ChoixPivot`, autrement dit tels que :
- ou bien `resultat_choix` est nul, et dans ce cas `EliminationPivot(A_choix, resultat_choix)` renvoie `(A_choix, resultat_choix)` ;
- ou bien le coefficient $(0, 0)$ de `A` est égal à $1$, et dans ce cas `EliminationPivot(A_choix, resultat_choix)` effectue les transvections nécessaires pour annuler tous les autres coefficients de la colonne $0$ de `A_choix`, renvoie la matrice ainsi obtenue et met à jour `resultat` en conséquence.

In [97]:
def EliminationPivot(A, resultat):
    
    if resultat == 0:
        return (A, 0)
    else:
        beta = -A[1:, 0]
        return SuiteTransvections(A, resultat, beta)

Tester la fonction `EliminationPivot(A, resultat)` sur les couples `(A_1_choix, resultat_1_choix)`, `(A_5_choix, resultat_5_choix)`, `(A_6_choix, resultat_6_choix)` et `(A_7_choix, resultat_7_choix)` ci-dessus.

In [98]:
print("(A_1_choix, resultat_1_choix) =\n", (A_1_choix, resultat_1_choix))
(A_1_elimination, resultat_1_elimination) = EliminationPivot(A_1_choix, resultat_1_choix)
print("(A_1_elimination, resultat_1_elimination) =\n", (A_1_elimination, resultat_1_elimination))

print("(A_5_choix, resultat_5_choix) =\n", (A_5_choix, resultat_5_choix))
(A_5_elimination, resultat_5_elimination) = EliminationPivot(A_5_choix, resultat_5_choix)
print("(A_5_elimination, resultat_5_elimination) =\n", (A_5_elimination, resultat_5_elimination))

print("(A_6_choix, resultat_6_choix) =\n", (A_6_choix, resultat_6_choix))
(A_6_elimination, resultat_6_elimination) = EliminationPivot(A_6_choix, resultat_6_choix)
print("(A_6_elimination, resultat_6_elimination) =\n", (A_6_elimination, resultat_6_elimination))

print("(A_7_choix, resultat_7_choix) =\n", (np.round(A_7_choix, 2), resultat_7_choix))
(A_7_elimination, resultat_7_elimination) = EliminationPivot(A_7_choix, resultat_7_choix)
print("(A_7_elimination, resultat_7_elimination) =\n", (np.round(A_7_elimination, 2), resultat_7_elimination))

(A_1_choix, resultat_1_choix) =
 (array([[ 1.        , -1.        ,  0.16666667],
       [ 5.        ,  0.        ,  3.        ],
       [ 0.        , -1.        ,  4.        ]]), -6.0)
(A_1_elimination, resultat_1_elimination) =
 (array([[ 1.        , -1.        ,  0.16666667],
       [ 0.        ,  5.        ,  2.16666667],
       [ 0.        , -1.        ,  4.        ]]), -6.0)
(A_5_choix, resultat_5_choix) =
 (array([[ 1. ,  0. , -0.5],
       [ 2. ,  4. , -1. ],
       [ 1. ,  2. ,  1. ]]), -4.0)
(A_5_elimination, resultat_5_elimination) =
 (array([[ 1. ,  0. , -0.5],
       [ 0. ,  4. ,  0. ],
       [ 0. ,  2. ,  1.5]]), -4.0)
(A_6_choix, resultat_6_choix) =
 (array([[ 0.        ,  1.        ,  0.        ],
       [ 0.        ,  1.        , -0.33333333],
       [ 0.        ,  0.        ,  1.        ]]), 0)
(A_6_elimination, resultat_6_elimination) =
 (array([[ 0.        ,  1.        ,  0.        ],
       [ 0.        ,  1.        , -0.33333333],
       [ 0.        ,  0.        ,

### 2.5. Calcul du déterminant par échelonnement

Définir de manière récursive une fonction `Echelonnement(A, resultat)` qui prend en argument une matrice carrée `A` de taille quelconque et un nombre `resultat`, et renvoie un couple `(A_triangulaire, resultat_triangulaire)` tel que :
- ou bien `resultat_triangulaire` est nul ;
- ou bien `A_triangulaire` est une matrice triangulaire supérieur avec des 1 sur la diagonale, obtenue par une suite d'opérations élémentaires sur la matrice `A`, et `resultat_triangulaire` est le nombre tel que le produit du déterminant de `A` et de `resultat` soit égal au produit du déterminant de `A_triangulaire` et de `resultat_triangulaire`.

In [109]:
def Echelonnement(A, resultat):
    # Solution
    (n, p) = np.shape(A)
    
    if n == 1:
        a = A[0, 0]
        
        if a == 0:
            return (A, 0)
        
        else:
            return (1 / a * A, a * resultat)
    
    else:
        (A_1, resultat_1) = ChoixPivot(A, resultat)
        (A_1, resultat_1) = EliminationPivot(A_1, resultat_1) 
        (A_1[1:, 1:], resultat_1) = Echelonnement(A_1[1:, 1:], resultat_1)
    
    return (A_1, resultat_1)
    # Fin solution

Tester la fonction `Echelonnement(A, resultat)` sur les matrices `A_1`, `A_5`, `A_6` et `A_7` ci-dessus et comparer aux résultats donnés par la fonction `np.linalg.det`.

In [110]:
print("A_1 =\n", A_1)
print("(A_1_triangulaire, resultat_1_triangulaire) =\n", Echelonnement(A_1, 1))
print("Vérification :", np.linalg.det(A_1))

print("A_5 =\n", A_5)
print("(A_5_triangulaire, resultat_5_triangulaire) =\n", Echelonnement(A_5, 1))
print("Vérification :", np.linalg.det(A_5))

print("A_6 =\n", A_6)
print("(A_6_triangulaire, resultat_6_triangulaire) =\n", Echelonnement(A_6, 1))
print("Vérification :", np.linalg.det(A_6))

print("A_7 =\n", np.round(A_7, 2))
(A_7_triangulaire, resultat_7_triangulaire) = Echelonnement(A_7, 1)
print("(A_7_triangulaire, resultat_7_triangulaire) =\n", (np.round(A_7_triangulaire, 2), resultat_7_triangulaire))
print("Vérification :", np.linalg.det(A_7))

A_1 =
 [[ 0. -1.  4.]
 [ 5.  0.  3.]
 [ 6. -6.  1.]]
(A_1_triangulaire, resultat_1_triangulaire) =
 (array([[ 1.        , -1.        ,  0.16666667],
       [ 0.        ,  1.        ,  0.43333333],
       [ 0.        ,  0.        ,  1.        ]]), -133.0)
Vérification : -133.0
A_5 =
 [[ 2.  4. -1.]
 [ 4.  0. -2.]
 [ 1.  2.  1.]]
(A_5_triangulaire, resultat_5_triangulaire) =
 (array([[ 1. ,  0. , -0.5],
       [ 0. ,  1. ,  0. ],
       [ 0. ,  0. ,  1. ]]), -24.0)
Vérification : -23.999999999999993
A_6 =
 [[ 0.          1.          0.        ]
 [ 0.          1.         -0.33333333]
 [ 0.          0.          1.        ]]
(A_6_triangulaire, resultat_6_triangulaire) =
 (array([[ 0.        ,  1.        ,  0.        ],
       [ 0.        ,  1.        , -0.33333333],
       [ 0.        ,  0.        ,  1.        ]]), 0.0)
Vérification : 0.0
A_7 =
 [[-0.89 -0.67 -0.18  0.66 -1.16 -1.33 -0.17  1.41  0.28]
 [ 0.63 -1.09  0.35  0.33 -0.   -0.14  1.21  0.43  1.55]
 [-0.17 -1.84  0.52 -0.21  0.91  

## 3. Développement suivant une rangée avec un maximum de zéros

En pratique, pour calculer le déterminant d'une matrice carrée de taille quelconque par développement suivant une rangée (ligne ou colonne), il est utile de minimiser le nombre d'opérations en choisissant à chaque fois la rangée (ligne ou colonne) avec le plus de zéros.

Écrire une fonction `MaxZeros(A)` qui prend en entrée une matrice carrée `A` de taille quelconque et qui renvoie un couple `(alpha, k)` égal à :
- $(0, k)$ si la **ligne** $k$ est la rangée contenant le plus de zéros ;
- $(1, k)$ si la **colonne** $k$ est la rangée contenant le plus de zéros.

Par exemple, si le résultat est la colonne $4$, la fonction retournera $(1, 4)$. On pourra utiliser la commande suivante : si `L` est une matrice ligne, `np.sum(L == 0)` renvoie le nombre de coefficients nuls dans `L`.

In [111]:
def MaxZeros(A):
    # Solution
    (n, p) = np.shape(A)
    alpha = 0
    k = 0
    m = 0
    
    for i in range(n):
        u = np.sum(A[i, :] == 0)
        if u > m:
            m = u
            k = i
    
    if m == n:
        return (alpha, k)
    
    else:
        for j in range(n):
            u = np.sum(A[:, j] == 0)
            if u > m:
                m = u
                k = j
                alpha = 1
    
    return (alpha, k)
    # Fin solution

Tester la fonction `MaxZeros(A)` sur les matrices $A_1$, $A_2$, $A_3$, $A_5$ (définies ci-dessus) et
$$
A_8 = \begin{pmatrix}
7 & -1 & 0 \\
5 & 0 & 3 \\
6 & -6 & 0
\end{pmatrix} .
$$

In [116]:
A_8 = np.array([[7, -1, 0], [5, 0, 3], [6, -6, 0]], dtype=float)

print(MaxZeros(A_1))
print(MaxZeros(A_2))
print(MaxZeros(A_3))
print(MaxZeros(A_5))
print(MaxZeros(A_8))

(0, 0)
(0, 0)
(0, 3)
(0, 1)
(1, 2)


Écrire une fonction `DeterminantMaxZeros(A)` qui prend en entrée une matrice carrée `A` de taille quelconque et qui renvoie le déterminant de `A` en développant à chaque fois suivant une rangée (ligne ou colonne) parmi celles qui ont le plus de zéros.

In [117]:
def DeterminantMaxZeros(A):
    # Solution
    (n, p) = np.shape(A)
    
    if n == 1:
        return A[0, 0]
    
    else :
        (alpha, k) = MaxZeros(A)
        det = 0
        
        if alpha == 0:
            A_1 = np.array(A)
            A_1 = np.delete(A_1, k, axis=0)
            for j in range(n):
                a = A[k, j]
                
                if a == 0:
                    continue
                
                else:
                    A_2 = np.delete(A_1, j, axis=1)
                    det += (-1)**(k + j) * a * DeterminantMaxZeros(A_2)
        else:
            A_1 = np.array(A)
            A_1 = np.delete(A_1, k, axis=1)
            for i in range(n):
                a = A[i, k]
                
                if a == 0:
                    continue
                
                else:
                    A_2 = np.delete(A_1, i, axis=0)
                    det += (-1)**(i + k) * a * DeterminantMaxZeros(A_2)
        
        return det
    # Fin solution

Testez la fonction `DeterminantMaxZeros(A)` sur les matrices $A_1$, $A_2$, $A_3$ et $A_4$ définies ci-dessus.

In [118]:
A_1 = np.array([[0, -1, 4], [5, 0, 3], [6, -6, 1]], dtype=float)
A_2 = np.array([[1, 4, -2], [1, -2, 4], [5, 7, 3]], dtype=float)
A_3 = np.array([[1, 4, 7, 10],[-2, 3.3, -14, 0], [1, 1.32, 7, 0.01], [0, -8, 0, 41]], dtype=float)
A_4 = np.array([[1, 5, 8, 1.5, 7, -8],
              [0, 7, 0, -2.2, 4, 0],
              [0, 0, -3, 1, -0.4, 5],
              [0, 0, 0, 2, 4, 11],
              [0, 0, 0, 0, 5, 2],
              [0, 0, 0, 0, 0, 1.5]], dtype=float)

print("det(A_1) =", DeterminantMaxZeros(A_1))
print("det(A_2) =", DeterminantMaxZeros(A_2))
print("det(A_3) =", DeterminantMaxZeros(A_3))
print("det(A_4) =", DeterminantMaxZeros(A_4))

det(A_1) = -133.0
det(A_2) = 0.0
det(A_3) = 0.0
det(A_4) = -315.0


## 4. Comparaison des différents algorithmes

Ci-dessous, on compare les temps de calculs des trois algorithmes implémentés pour le calcul du déterminant, ainsi que celui de la fonction `np.linalg.det`.

In [119]:
from time import time

# Matrice aléatoire quelconque

print("Matrice aléatoire quelconque :")
E = np.random.rand(8, 8)
print("E =\n", np.round(E, 2))

debut = time()
determinant(E)
fin = time()
print("%.6f" %(fin - debut), "(durée par développement suivant la première ligne)")

debut = time()
Echelonnement(E, 1)
fin = time()
print("%.6f" %(fin - debut), "(durée par l'algorithme du pivot de Gauss)")

debut = time()
DeterminantMaxZeros(E)
fin = time()
print("%.6f" %(fin - debut), "(durée par développement suivant une rangée contenant un maximum de zéros)")

debut = time()
np.linalg.det(E)
fin = time()
print("%.6f" %(fin - debut), "(durée par np.linalg.det)")


# Matrice creuse aléatoire

print("\nMatrice creuse aléatoire :")
F = np.random.rand(8, 8)
F[F < 0.7] = 0
print("F =\n", np.round(F, 2))

debut = time()
determinant(F)
fin = time()
print("%.6f" %(fin - debut), "(durée par développement suivant la première ligne)")

debut = time()
Echelonnement(F, 1)
fin = time()
print("%.6f" %(fin - debut), "(durée par l'algorithme du pivot de Gauss)")

debut = time()
DeterminantMaxZeros(F)
fin = time()
print("%.6f" %(fin - debut), "(durée par développement suivant une rangée contenant un maximum de zéros)")

debut = time()
np.linalg.det(F)
fin = time()
print("%.6f" %(fin - debut), "(durée par np.linalg.det)")


# Matrice triangulaire supérieure aléatoire

print("\nMatrice triangulaire supérieure aléatoire :")
G = np.random.rand(8, 8)
G = np.triu(G)
print("G =\n", np.round(G, 2))

debut = time()
determinant(G)
fin = time()
print("%.6f" %(fin - debut), "(durée par développement suivant la première ligne)")

debut = time()
Echelonnement(G, 1)
fin = time()
print("%.6f" %(fin - debut), "(durée par l'algorithme du pivot de Gauss)")

debut = time()
DeterminantMaxZeros(G)
fin = time()
print("%.6f" %(fin - debut), "(durée par développement suivant une rangée contenant un maximum de zéros)")

debut = time()
np.linalg.det(G)
fin = time()
print("%.6f" %(fin - debut), "(durée par np.linalg.det)")

Matrice aléatoire quelconque :
E =
 [[0.88 0.74 0.32 0.69 0.12 0.55 0.88 0.98]
 [0.95 0.41 0.99 0.71 0.76 0.8  0.63 0.4 ]
 [0.93 0.78 0.92 0.4  0.57 0.81 0.8  0.25]
 [0.77 0.27 0.62 0.76 0.88 0.4  0.78 0.46]
 [0.59 0.61 0.77 0.72 0.4  0.24 0.31 0.02]
 [0.01 0.21 0.3  0.88 0.85 0.17 0.53 0.34]
 [0.55 0.68 0.78 0.76 0.19 0.86 0.95 0.38]
 [0.79 0.53 0.07 0.3  0.12 0.03 0.85 0.8 ]]
0.464169 (durée par développement suivant la première ligne)
0.000000 (durée par l'algorithme du pivot de Gauss)
1.212573 (durée par développement suivant une rangée contenant un maximum de zéros)
0.000000 (durée par np.linalg.det)

Matrice creuse aléatoire :
F =
 [[0.   0.   0.82 0.   0.   0.   0.   0.  ]
 [0.98 0.   0.87 0.   0.   0.   0.   0.75]
 [0.   0.7  0.82 0.   0.82 0.   0.   0.  ]
 [0.   0.81 0.   0.   0.82 0.   0.88 0.  ]
 [0.   0.   0.   0.   0.85 0.95 0.72 0.  ]
 [0.   0.96 0.   0.   0.   0.   0.   0.88]
 [0.   0.   0.79 0.   0.   0.   0.   0.75]
 [0.   0.   0.   0.71 0.   0.   0.   0.  ]]
0.490750 